package br.ufrpe.bugzilla.gui.telas;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXButton;

import br.ufrpe.bugzilla.gui.login.LoginAdministradorController;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class TelaEncomendaController implements Initializable{
	@FXML
	private ImageView home;
	@FXML
	private ImageView funcBtn;
	@FXML
	private ImageView encBtn;
	@FXML
	private ImageView centralBtn;
	@FXML
	private ImageView clienteBtn;
	@FXML
	private Label nomeFuncOuAdm;
	@FXML
	private JFXButton buscar_enc;
	@FXML
	private JFXButton alterar_enc;
	@FXML
	private JFXButton remover_enc;
	@FXML
	private JFXButton listar_enc;
	@FXML
	private JFXButton add_enc;

	// Event Listener on ImageView[#home].onMouseClicked
	@FXML
	public void home(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#funcBtn].onMouseClicked
	@FXML
	public void funcOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#encBtn].onMouseClicked
	@FXML
	public void encOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#centralBtn].onMouseClicked
	@FXML
	public void centralOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#clienteBtn].onMouseClicked
	@FXML
	public void clienteOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#buscar_enc].onAction
	@FXML
	public void buscarEnc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#alterar_enc].onAction
	@FXML
	public void alterarEnc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#remover_enc].onAction
	@FXML
	public void removerEnc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#listar_enc].onAction
	@FXML
	public void listarEnc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#add_enc].onAction
	@FXML
	public void addEnc(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void initialize(URL location, ResourceBundle resources) {
		
		this.nomeFuncOuAdm.setText(LoginAdministradorController.getNome());
	}
}
