package br.ufrpe.bugzilla.gui.telas;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXButton;

import br.ufrpe.bugzilla.gui.login.LoginAdministradorController;
import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class TelaFuncionarioController implements Initializable{
	@FXML
	private ImageView home;
	@FXML
	private ImageView funcBtn;
	@FXML
	private ImageView encBtn;
	@FXML
	private ImageView centralBtn;
	@FXML
	private ImageView clienteBtn;
	@FXML
	private Label nomeFuncOuAdm;
	@FXML
	private JFXButton add_func;
	@FXML
	private JFXButton buscar_func;
	@FXML
	private JFXButton alterar_func;
	@FXML
	private JFXButton remover_func;
	@FXML
	private JFXButton listar_func;

	// Event Listener on ImageView[#home].onMouseClicked
	@FXML
	public void home(MouseEvent event) {

		Parent p1 = null;
		
		try{
			p1 = FXMLLoader.load(getClass().getResource("TelaInicial.fxml"));
			Stage stage = (Stage) ((Node) (event.getSource())).getScene().getWindow();
			Scene scene = new Scene(p1);
			stage.setScene(scene);
			stage.setTitle("Bugzilla Encomendas");
			stage.show();
			
		}catch(Exception e){
			e.printStackTrace();
		}
	}
	// Event Listener on ImageView[#encBtn].onMouseClicked
		@FXML
		public void encOpcoes(MouseEvent event) {
			
			Parent p1 = null;
			
			try{
				p1 = FXMLLoader.load(getClass().getResource("TelaEncomenda.fxml"));
				Stage stage = (Stage) ((Node) (event.getSource())).getScene().getWindow();
				Scene scene = new Scene(p1);
				stage.setScene(scene);
				stage.setTitle("Bugzilla Encomendas");
				stage.show();
				
			}catch(Exception e){
				e.printStackTrace();
			}
		}
		// Event Listener on ImageView[#centralBtn].onMouseClicked
		@FXML
		public void centralOpcoes(MouseEvent event) {

			Parent p1 = null;
			
			try{
				p1 = FXMLLoader.load(getClass().getResource("TelaCentral.fxml"));
				Stage stage = (Stage) ((Node) (event.getSource())).getScene().getWindow();
				Scene scene = new Scene(p1);
				stage.setScene(scene);
				stage.setTitle("Bugzilla Encomendas");
				stage.show();
				
			}catch(Exception e){
				e.printStackTrace();
			}
		}
		// Event Listener on ImageView[#clienteBtn].onMouseClicked
		@FXML
		public void clienteOpcoes(MouseEvent event) {

			Parent p1 = null;
			
			try{
				p1 = FXMLLoader.load(getClass().getResource("TelaCliente.fxml"));
				Stage stage = (Stage) ((Node) (event.getSource())).getScene().getWindow();
				Scene scene = new Scene(p1);
				stage.setScene(scene);
				stage.setTitle("Bugzilla Encomendas");
				stage.show();
				
			}catch(Exception e){
				e.printStackTrace();
			}
		}
	// Event Listener on JFXButton[#add_func].onAction
	@FXML
	public void addFunc(ActionEvent event) {
		((Node) (event.getSource())).getScene().getWindow().hide();
		Parent p = null;
		
		try {
			p = FXMLLoader.load(getClass().getResource("CadastroFuncionario.fxml"));
			Scene scene = new Scene(p);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.setTitle("Bugzilla Encomendas");
			stage.show();
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
	}
	// Event Listener on JFXButton[#buscar_func].onAction
	@FXML
	public void buscarFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#alterar_func].onAction
	@FXML
	public void alterarFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#remover_func].onAction
	@FXML
	public void removerFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#listar_func].onAction
	@FXML
	public void listarFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	public void initialize(URL arg0, ResourceBundle arg1) {
		
		this.nomeFuncOuAdm.setText(LoginAdministradorController.getNome());
	}
}
