package br.ufrpe.bugzilla.gui.telas;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXButton;

import br.ufrpe.bugzilla.gui.login.LoginAdministradorController;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class TelaCentralController implements Initializable{
	@FXML
	private ImageView home;
	@FXML
	private ImageView funcBtn;
	@FXML
	private ImageView encBtn;
	@FXML
	private ImageView centralBtn;
	@FXML
	private ImageView clienteBtn;
	@FXML
	private Label nomeFuncOuAdm;
	@FXML
	private JFXButton add_central;
	@FXML
	private JFXButton listar_central;
	@FXML
	private JFXButton remover_central;
	@FXML
	private JFXButton alterar_central;
	@FXML
	private JFXButton buscar_central;

	// Event Listener on ImageView[#home].onMouseClicked
	@FXML
	public void home(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#funcBtn].onMouseClicked
	@FXML
	public void funcOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#encBtn].onMouseClicked
	@FXML
	public void encOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#centralBtn].onMouseClicked
	@FXML
	public void centralOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#clienteBtn].onMouseClicked
	@FXML
	public void clienteOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#add_central].onAction
	@FXML
	public void addCentral(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#listar_central].onAction
	@FXML
	public void listarCentral(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#remover_central].onAction
	@FXML
	public void removerCentral(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#alterar_central].onAction
	@FXML
	public void alterarCentral(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#buscar_central].onAction
	@FXML
	public void buscarCentral(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void initialize(URL location, ResourceBundle resources) {
		
		this.nomeFuncOuAdm.setText(LoginAdministradorController.getNome());
	}
}
