package br.ufrpe.bugzilla.gui;

import java.net.URL;
import java.util.ResourceBundle;

import br.ufrpe.bugzilla.negocio.Fachada;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Label;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class TelaInicialFuncionarioController implements Initializable{
	@FXML
	private ImageView home;
	@FXML
	private ImageView encBtn;
	@FXML
	private ImageView centralBtn;
	@FXML
	private ImageView clienteBtn;
	@FXML
	private Label nomeFuncOuAdm;
	@FXML
	private Label numCliente;
	@FXML
	private Label numCentral;
	@FXML
	private Label numEnc;

	// Event Listener on ImageView[#home].onMouseClicked
	@FXML
	public void home(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#encBtn].onMouseClicked
	@FXML
	public void encOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#centralBtn].onMouseClicked
	@FXML
	public void centralOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#clienteBtn].onMouseClicked
	@FXML
	public void clienteOpcoes(MouseEvent event) {
		// TODO Autogenerated
	}
	public void initialize(URL location, ResourceBundle resources) {
		
		this.numCentral.setText(String.valueOf(Fachada.getInstance().contadorCentral()));
		this.numCliente.setText(String.valueOf(Fachada.getInstance().contadorEncomenda()));
		this.numEnc.setText(String.valueOf(Fachada.getInstance().contadorEncomenda()));
		
		this.nomeFuncOuAdm.setText(LoginFuncionarioController.getNome());
	}
}
